# Generated by Django 4.0.1 on 2023-06-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='Phone',
        ),
    ]
