# Generated by Django 4.2 on 2023-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('phone_Number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('cab', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('pinCode', models.CharField(max_length=10)),
                ('Text', models.CharField(max_length=100)),
                ('passengers', models.CharField(max_length=100)),
                ('TimeStart', models.CharField(max_length=100)),
                ('TimeEnd', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
