# Generated by Django 4.2 on 2023-06-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='phone_number',
            new_name='phone_Number',
        ),
    ]
